registries:
  energy-origin:
    url: https://energytrackandtrace-dk.updatewalletv162.p.acorn-dev.dk/
areas:
  DK1:
    issuerKeys:
    - publicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQVM1OG1JZlRNN2M3bDBjVzN2VkpyRU5wWDcwTU0vTU5FQmZHNy9ycDdERjA9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
  DK2:
    issuerKeys:
    - publicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQUFkOEUzRXVEbG90dExOTllrbTBVZFdNUDYwTmR6VFRiYjVkanlwUEVkc009Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
